### ISSUE TITLE
Can't split a complex128 tensor

### ISSUE THREAD

**Issue by philipollaswilson** [joserapa98/tensorkrowch#2]
Hey there, I get an error when I try to split a complex tensor. Am I doing something wrong?
Thanks!

```
net = tk.TensorNetwork()

node1 = tk.Node(tensor=tensors[0],
                 axes_names=('left', 'a', 'o', 'right'),
                 name='node1',
                 network=net)
print(tensors[0].dtype)
t1a, t1o = tk.split_(node1, ['left','a'], [ 'o', 'right'],mode='svd')
```

![image](https://github.com/joserapa98/tensorkrowch/assets/49437234/15753330-1ac4-4535-9c2c-d197e43e771a)

**Comment by joserapa98** [comment]
Hey! Thanks for bringing up this issue. Your code is perfectly fine. It fails because `torch.linalg.svd` returns the singular values as `torch.float32`, and the unitary matrices `U` and `Vh` as `torch.complex64` when the input tensor is complex.

I didn't expect that and honestly didn't test it. I've just released a new version, `1.1.4`, fixing this issue, adding more support for specifying the `dtype` of the nodes' tensors, and including many tests for the case of complex tensors.
